Resources:
  ProductsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.productsTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1